"""
Backtest harness for the Varsity equity-swing strategy.

Replay model
------------
Walk the OHLCV panel one trading day at a time. On each date:
  1. ``check_and_rehedge`` runs first — exits triggered (SL hit during the
     day, target hit, time stop, Chandelier trail). Exit fills happen at the
     stop / target price (intraday touch model) or at the close for time
     stops.
  2. ``scan_and_propose`` runs at the close. Proposals are queued for the
     next trading day's **open** to avoid look-ahead — a strategy that sees
     today's close and trades today's close is fitting in-sample.

Costs
-----
Round-trip fees applied on each completed trade:
  * Brokerage: free (Zerodha delivery flat 0)
  * STT delivery sell-side: 0.1 %
  * Exchange tx + SEBI + GST stack: ~0.0035 % each side
  * Stamp duty (buy): 0.015 %
  * Slippage: 0.05 % each side (configurable)

Total RT cost ≈ **0.20 %** of notional, applied symmetrically. This is
generous compared to live execution but matches the Varsity calendar lesson
(`tasks/lessons.md`): err on the conservative side so the backtest never
flatters live results.

Scoring sentinels
-----------------
``ZERO_TRADE_PENALTY = -1e6`` returned when no trades fire (so an
autoresearch sweep can't mistake "no signal" for "neutral score" — see the
flat-fitness lesson).

CLI::

    python -m research.backtest_varsity_equity
    python -m research.backtest_varsity_equity --short-window 20 --long-window 50
    python -m research.backtest_varsity_equity --capital 2000000 --start 2025-12-01
"""
from __future__ import annotations

import argparse
import json
import logging
import math
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


from strategies._eq_data import load_equity_panel, load_universe
from core.backtest_timeframe import warn_coarse_timeframe
from strategies.varsity_equity_swing import (
    EquityPosition,
    PENDING_GAP_ATR_THRESHOLD,
    PENDING_MAX_AGE_DAYS,
    VarsityEquitySwingStrategy,
)

logger = logging.getLogger(__name__)

ZERO_TRADE_PENALTY = -1e6

ROUND_TRIP_COST_PCT = 0.20  # 0.10% sell STT + ~0.10% slippage+GST/exchange/stamp


@dataclass
class TradeRecord:
    symbol: str
    entry_dt: pd.Timestamp
    entry_px: float
    qty: int
    exit_dt: pd.Timestamp
    exit_px: float
    exit_reason: str
    gross_pnl: float
    costs: float
    net_pnl: float
    holding_days: int
    R_multiple: float  # net_pnl / risk_at_entry


# ──────────────────────────────────────────────────────────────────────────────
# Replay engine
# ──────────────────────────────────────────────────────────────────────────────

class EquityBacktester:
    """Walk-forward replay of VarsityEquitySwingStrategy over an OHLCV panel."""

    def __init__(
        self,
        panel: pd.DataFrame,
        params_overrides: Optional[Dict] = None,
        cost_pct: float = ROUND_TRIP_COST_PCT,
    ):
        self.panel = panel
        self.cost_pct = cost_pct

        class _NullKite:
            pass
        # Strategy in paper mode, in-memory book.
        self.strategy = VarsityEquitySwingStrategy(
            kite=_NullKite(), config_path="/dev/null", mode="paper",
        )
        if params_overrides:
            self.strategy.params.update(params_overrides)
        self.strategy.set_panel(panel, sorted(panel["symbol"].unique().tolist()))
        self.strategy._ensure_features()

        self.trade_log: List[TradeRecord] = []
        self.equity_curve: List[Tuple[pd.Timestamp, float]] = []
        self.daily_returns: List[float] = []
        # EQ-FU-2 instrumentation — counts gap-skip and stale-skip drops
        # for the summary. autoresearch consumers can read these to spot
        # parameter sweeps where the would-be trade count is artificially
        # inflated by the live-vs-backtest filter gap.
        self.n_skipped_gap: int = 0
        self.n_skipped_stale: int = 0

    def _trading_dates(self) -> List[pd.Timestamp]:
        return sorted(self.panel["date"].unique().tolist())

    def _open_price(self, sym: str, dt: pd.Timestamp) -> Optional[float]:
        f = self.strategy._features.get(sym)
        if f is None or dt not in f.index:
            return None
        v = f.loc[dt, "open"]
        return None if pd.isna(v) else float(v)

    def _fill_queued(self, dt: pd.Timestamp,
                      queued: List[Tuple], cash: float) -> float:
        """EQ-FU-2 fill loop, extracted from run() so tests can drive the
        real production logic instead of re-implementing it.

        `queued` is the list of (proposal, signal_dt) tuples generated by
        yesterday's close-scan. Applies the SAME filters as live's
        _fill_pending_entries:
          - panel missing / non-positive open → SKIPPED_STALE
          - age > PENDING_MAX_AGE_DAYS         → SKIPPED_STALE
          - gap > PENDING_GAP_ATR_THRESHOLD    → SKIPPED_GAP
        Books position and mutates cash on a clean fill; counters
        (n_skipped_gap / n_skipped_stale) increment on each skip.
        Returns the new cash balance.
        """
        for proposal, signal_dt in queued:
            open_px = self._open_price(proposal.tradingsymbol, dt)
            if open_px is None or open_px <= 0:
                self.n_skipped_stale += 1
                continue
            age_days = (dt - signal_dt).days
            if age_days > PENDING_MAX_AGE_DAYS:
                # Stale: live would mark SKIPPED_STALE. In a clean
                # daily-step backtest this branch never fires (age==1)
                # unless the panel skips days; kept for Rule 7 parity.
                self.n_skipped_stale += 1
                continue
            snap = proposal.greeks_snapshot or {}
            atr_v = float(snap.get("atr", 0.0))
            signal_close = float(snap.get("entry", 0.0))
            if atr_v > 0 and signal_close > 0:
                gap_atr = abs(open_px - signal_close) / atr_v
                if gap_atr > PENDING_GAP_ATR_THRESHOLD:
                    self.n_skipped_gap += 1
                    continue
            # cost on entry
            notional = open_px * proposal.quantity
            entry_cost = notional * self.cost_pct / 200.0  # half RT on entry
            cash -= notional + entry_cost
            # rebuild SL/target around the actual fill (not yesterday's close)
            k_sl = self.strategy.params["atr_stop_multiplier"]
            rr = self.strategy.params["risk_reward"]
            sl = open_px - k_sl * atr_v
            target = open_px + rr * k_sl * atr_v
            pos = EquityPosition(
                symbol=proposal.tradingsymbol, side="LONG",
                entry_dt=dt, entry_px=open_px, qty=proposal.quantity,
                initial_sl=sl, target=target, atr_at_entry=atr_v,
                rationale=proposal.rationale,
            )
            self.strategy.positions[proposal.tradingsymbol] = pos
        return cash

    def run(self) -> Dict:
        dates = self._trading_dates()
        if not dates:
            raise RuntimeError("empty panel — cannot backtest")
        capital = self.strategy.params["total_capital"]
        cash = capital
        # EQ-FU-2: queue carries (proposal, signal_dt) tuples so the
        # max-age filter (PENDING_MAX_AGE_DAYS) is computable. signal_dt
        # is the date of the close-scan that emitted the proposal.
        queued: List[Tuple] = []

        for i, dt in enumerate(dates):
            self.strategy.set_current_date(dt)

            # 1) Execute queued opens at today's open. EQ-FU-2 applies the
            # SAME gap-skip + max-age filters as live's _fill_pending_entries,
            # so autoresearch sweeps optimise against the trade count that
            # live will actually deliver.
            cash = self._fill_queued(dt, queued, cash)
            queued = []

            # 2) Run intraday exit checks against today's high/low
            exits = self.strategy.check_and_rehedge()
            for ex in exits:
                pos = self.strategy.positions.pop(ex.tradingsymbol, None)
                if pos is None:
                    continue
                exit_px = ex.price
                notional_exit = exit_px * pos.qty
                exit_cost = notional_exit * self.cost_pct / 200.0  # half RT on exit
                cash += notional_exit - exit_cost
                gross_pnl = (exit_px - pos.entry_px) * pos.qty
                costs = (pos.entry_px * pos.qty + exit_px * pos.qty) * self.cost_pct / 200.0 * 2
                net_pnl = gross_pnl - (
                    pos.entry_px * pos.qty * self.cost_pct / 200.0
                    + exit_px * pos.qty * self.cost_pct / 200.0
                )
                holding = self.strategy._trading_days_between(pos.entry_dt, dt)
                risk_at_entry = (pos.entry_px - pos.initial_sl) * pos.qty
                rmult = (net_pnl / risk_at_entry) if risk_at_entry > 0 else 0.0
                pos.exit_dt = dt
                pos.exit_px = exit_px
                pos.exit_reason = (ex.greeks_snapshot or {}).get("exit_reason", "MANUAL")
                pos.pnl = net_pnl
                pos.status = "CLOSED"
                self.strategy.closed_positions.append(pos)
                self.trade_log.append(TradeRecord(
                    symbol=pos.symbol, entry_dt=pos.entry_dt, entry_px=pos.entry_px,
                    qty=pos.qty, exit_dt=dt, exit_px=exit_px,
                    exit_reason=pos.exit_reason,
                    gross_pnl=gross_pnl, costs=costs, net_pnl=net_pnl,
                    holding_days=holding, R_multiple=rmult,
                ))

            # 3) Scan at close for tomorrow's entries. EQ-FU-2: tag each
            # proposal with today's date so the next-day filler can apply
            # the same max-age filter live uses.
            proposals = self.strategy.scan_and_propose()
            queued = [(p, dt) for p in proposals]

            # 4) Mark equity curve at today's close
            mtm = sum(self._mtm_value(p, dt) for p in self.strategy.positions.values())
            equity = cash + mtm
            self.equity_curve.append((dt, equity))
            if i > 0:
                prev_eq = self.equity_curve[i-1][1]
                if prev_eq > 0:
                    self.daily_returns.append((equity - prev_eq) / prev_eq)

        return self.summary()

    def _mtm_value(self, pos: EquityPosition, dt: pd.Timestamp) -> float:
        f = self.strategy._features.get(pos.symbol)
        if f is None or dt not in f.index:
            return pos.entry_px * pos.qty
        close = f.loc[dt, "close"]
        if pd.isna(close):
            return pos.entry_px * pos.qty
        return float(close) * pos.qty

    # ── Reporting ──────────────────────────────────────────────────────────

    def summary(self) -> Dict:
        n = len(self.trade_log)
        if n == 0:
            return {
                "total_trades": 0,
                "score": ZERO_TRADE_PENALTY,
                "note": "no trades fired — see lessons.md flat-fitness rule",
                "n_skipped_gap": self.n_skipped_gap,
                "n_skipped_stale": self.n_skipped_stale,
            }
        wins = [t for t in self.trade_log if t.net_pnl > 0]
        losses = [t for t in self.trade_log if t.net_pnl <= 0]
        gross = sum(t.gross_pnl for t in self.trade_log)
        net = sum(t.net_pnl for t in self.trade_log)
        avg_win = sum(t.net_pnl for t in wins) / len(wins) if wins else 0.0
        avg_loss = sum(t.net_pnl for t in losses) / len(losses) if losses else 0.0
        win_rate = len(wins) / n
        profit_factor = (
            sum(t.net_pnl for t in wins) / abs(sum(t.net_pnl for t in losses))
            if losses and sum(t.net_pnl for t in losses) != 0 else float("inf")
        )
        avg_hold = sum(t.holding_days for t in self.trade_log) / n
        avg_R = sum(t.R_multiple for t in self.trade_log) / n
        # Equity-curve metrics
        rets = np.array(self.daily_returns) if self.daily_returns else np.array([0.0])
        ann = math.sqrt(252)
        sharpe = (rets.mean() / rets.std() * ann) if rets.std() > 1e-9 else 0.0
        # drawdown
        equity = np.array([eq for _, eq in self.equity_curve])
        peak = np.maximum.accumulate(equity)
        dd = (equity - peak) / peak
        max_dd = float(dd.min()) if len(dd) else 0.0
        # CAGR
        n_days = len(self.equity_curve)
        cagr = ((equity[-1] / equity[0]) ** (252.0 / n_days) - 1.0) if n_days > 1 else 0.0
        calmar = (cagr / abs(max_dd)) if max_dd < 0 else float("inf")

        return {
            "total_trades": n,
            "win_rate": round(win_rate, 4),
            "profit_factor": round(profit_factor, 3) if math.isfinite(profit_factor) else None,
            "avg_win": round(avg_win, 2),
            "avg_loss": round(avg_loss, 2),
            "avg_R": round(avg_R, 3),
            "avg_holding_days": round(avg_hold, 2),
            "gross_pnl": round(gross, 2),
            "net_pnl": round(net, 2),
            "sharpe": round(float(sharpe), 3),
            "max_drawdown_pct": round(max_dd * 100, 2),
            "cagr_pct": round(cagr * 100, 2),
            "calmar": round(float(calmar), 3) if math.isfinite(calmar) else None,
            "starting_equity": round(self.equity_curve[0][1], 2) if self.equity_curve else None,
            "ending_equity": round(self.equity_curve[-1][1], 2) if self.equity_curve else None,
            "n_dates": len(self.equity_curve),
            "score": float(sharpe),
            # EQ-FU-2: visibility into how many signals the live filter
            # would have dropped. autoresearch dashboards can plot the
            # filter-rate so a parameter sweep that yields high backtest
            # PnL but high gap-skip rate is flagged as "live will fire
            # fewer trades than the screen suggests".
            "n_skipped_gap": self.n_skipped_gap,
            "n_skipped_stale": self.n_skipped_stale,
        }

    def per_symbol_breakdown(self) -> pd.DataFrame:
        if not self.trade_log:
            return pd.DataFrame()
        rows = []
        for t in self.trade_log:
            rows.append({"symbol": t.symbol, "net_pnl": t.net_pnl,
                         "R": t.R_multiple, "hold": t.holding_days,
                         "exit": t.exit_reason})
        df = pd.DataFrame(rows)
        agg = df.groupby("symbol").agg(
            trades=("net_pnl", "count"),
            wins=("net_pnl", lambda s: int((s > 0).sum())),
            net_pnl=("net_pnl", "sum"),
            avg_R=("R", "mean"),
            avg_hold=("hold", "mean"),
        ).sort_values("net_pnl", ascending=False)
        return agg


# ──────────────────────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────────────────────

def main():
    logging.basicConfig(level=logging.WARNING, format="%(asctime)s %(levelname)-8s %(message)s")

    p = argparse.ArgumentParser(description="Varsity equity-swing backtest")
    p.add_argument("--universe", default="data_cache/nifty200.csv")
    p.add_argument("--source", default="auto", choices=["auto", "cache", "stf"],
                   help="OHLCV source preference (default auto: per-symbol cache then STF proxy)")
    p.add_argument("--start", default=None, help="YYYY-MM-DD inclusive")
    p.add_argument("--end", default=None, help="YYYY-MM-DD inclusive")
    p.add_argument("--capital", type=float, default=1_000_000.0)
    p.add_argument("--risk-pct", type=float, default=1.0)
    p.add_argument("--short-window", type=int, default=None)
    p.add_argument("--long-window", type=int, default=None)
    p.add_argument("--adx-threshold", type=float, default=None)
    p.add_argument("--atr-stop", type=float, default=None)
    p.add_argument("--rr", type=float, default=None)
    p.add_argument("--time-stop", type=int, default=None)
    p.add_argument("--cost-pct", type=float, default=ROUND_TRIP_COST_PCT)
    p.add_argument("--mp", choices=["off", "on"], default="on",
                   help="Phase-2 Market Profile gate (default: on)")
    p.add_argument("--oi", choices=["off", "on"], default="off",
                   help="Phase-2 OI confluence gate (default: off — see DEFAULTS rationale)")
    p.add_argument("--ledger-out", default="data_cache/equity_swing_trades.tsv")
    p.add_argument("--report-json", default=None)
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args()

    warn_coarse_timeframe("daily", backtest="backtest_varsity_equity",
                          reason="no 5-min equity data exists — daily EOD panel "
                          "only; stand up forward 5-min capture (issue #63)")

    universe = load_universe(Path(args.universe))
    panel = load_equity_panel(universe=universe, source=args.source)
    if args.start:
        panel = panel[panel["date"] >= pd.Timestamp(args.start)]
    if args.end:
        panel = panel[panel["date"] <= pd.Timestamp(args.end)]
    if panel.empty:
        print("ERROR: panel empty after date filter", file=sys.stderr)
        return 2

    overrides = {"total_capital": args.capital, "risk_per_trade_pct": args.risk_pct}
    if args.short_window:    overrides["trend_short_window"]   = args.short_window
    if args.long_window:     overrides["trend_long_window"]    = args.long_window
    if args.adx_threshold is not None: overrides["adx_threshold"] = args.adx_threshold
    if args.atr_stop is not None:      overrides["atr_stop_multiplier"] = args.atr_stop
    if args.rr is not None:            overrides["risk_reward"] = args.rr
    if args.time_stop is not None:     overrides["time_stop_days"] = args.time_stop
    overrides["mp_enabled"] = 1 if args.mp == "on" else 0
    overrides["oi_enabled"] = 1 if args.oi == "on" else 0

    bt = EquityBacktester(panel, params_overrides=overrides, cost_pct=args.cost_pct)
    summary = bt.run()

    print("=" * 78)
    print("Varsity Equity Swing — Backtest Summary")
    print("=" * 78)
    print(f"  Universe          : {len(universe)} symbols")
    print(f"  Date range        : {panel['date'].min().date()} → {panel['date'].max().date()}")
    print(f"  Trading days      : {summary.get('n_dates', 0)}")
    print(f"  Trend windows     : {bt.strategy.params['trend_short_window']:.0f} / "
          f"{bt.strategy.params['trend_long_window']:.0f}")
    print(f"  ADX threshold     : {bt.strategy.params['adx_threshold']:.0f}")
    print(f"  ATR stop / RR     : {bt.strategy.params['atr_stop_multiplier']:.1f}× / "
          f"{bt.strategy.params['risk_reward']:.1f}")
    print(f"  MP gate / OI gate : {'on ' if args.mp == 'on' else 'off'} / "
          f"{'on ' if args.oi == 'on' else 'off'}")
    print(f"  Round-trip cost   : {args.cost_pct:.2f} %")
    print("-" * 78)
    if summary["total_trades"] == 0:
        print(f"  No trades fired. Score sentinel: {summary['score']}")
        print("  Likely cause: warm-up too long for the available history")
        print(f"  (need {bt.strategy.params['trend_long_window']:.0f}+ bars before SMA-long evaluates).")
        return 1
    print(f"  Total trades      : {summary['total_trades']}")
    print(f"  Win rate          : {summary['win_rate']*100:.1f} %")
    print(f"  Profit factor     : {summary['profit_factor']}")
    print(f"  Avg R-multiple    : {summary['avg_R']}")
    print(f"  Avg holding days  : {summary['avg_holding_days']}")
    print(f"  Net P&L           : ₹{summary['net_pnl']:>14,.0f}")
    print(f"  Avg win / loss    : ₹{summary['avg_win']:>10,.0f}  /  ₹{summary['avg_loss']:>10,.0f}")
    print(f"  Sharpe (ann.)     : {summary['sharpe']}")
    print(f"  Max drawdown      : {summary['max_drawdown_pct']} %")
    print(f"  CAGR              : {summary['cagr_pct']} %")
    print(f"  Calmar            : {summary['calmar']}")
    print(f"  Equity            : ₹{summary['starting_equity']:>14,.0f}  →  "
          f"₹{summary['ending_equity']:>14,.0f}")
    print("-" * 78)

    # Exit-reason breakdown
    if not args.quiet and bt.trade_log:
        from collections import Counter
        c = Counter(t.exit_reason for t in bt.trade_log)
        print("  Exit reasons      : " + ", ".join(f"{k}={v}" for k, v in c.most_common()))

    # Per-symbol breakdown (top 10 + bottom 5)
    if not args.quiet:
        per = bt.per_symbol_breakdown()
        if not per.empty:
            print("-" * 78)
            print("  Top 10 winners (net ₹):")
            print(per.head(10).to_string())
            if len(per) > 10:
                print("\n  Bottom 5 losers (net ₹):")
                print(per.tail(5).to_string())

    # Per-trade ledger TSV
    if bt.trade_log:
        ledger = pd.DataFrame([t.__dict__ for t in bt.trade_log])
        ledger.to_csv(args.ledger_out, sep="\t", index=False)
        print("-" * 78)
        print(f"  Per-trade ledger  : {args.ledger_out}")

    if args.report_json:
        Path(args.report_json).write_text(json.dumps(summary, indent=2, default=str))
        print(f"  Summary JSON      : {args.report_json}")

    print("=" * 78)
    return 0


if __name__ == "__main__":
    sys.exit(main())
